version: '3.8'

services:
  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - OLLAMA_HOST=${OLLAMA_HOST:-localhost}
    restart: unless-stopped 